name: CI
on: [push, pull_request]

jobs:
  rdflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: ./
      - run: rdflint -v
