name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rdflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - uses: ./
      - run: rdflint -v

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
